"""Automated test suite for Exotel AgentStream voice bot WebSocket integration in RESCURO.

Tests:
1. Audio format transcoding (PCM16 8kHz <-> G.711 u-law).
2. Silence detection: pure silence chunks do NOT trigger premature turns or response loops.
3. Turn detection: speech chunks followed by silence trigger exactly ONE response turn.
4. Telephony events: connected, start, dtmf, mark, clear, stop.
5. Database session persistence (EXO- prefix).
6. Non-regression of existing routes.
"""

import json
import base64
import struct
import time
import pytest
from fastapi.testclient import TestClient
from app.main import app
from app.services.tts_service import pcm16_to_ulaw, ulaw_to_pcm16
from app.database import get_call_sessions

client = TestClient(app)


def test_exotel_pcm16_ulaw_transcoding_helpers():
    """Verify pcm16_to_ulaw and ulaw_to_pcm16 roundtrip and byte sizing."""
    # 160 samples of 16-bit PCM = 320 bytes
    pcm16_sample = b"\x00\x00" * 160
    assert len(pcm16_sample) == 320

    ulaw = pcm16_to_ulaw(pcm16_sample)
    # 8-bit u-law should be exactly 160 bytes
    assert len(ulaw) == 160

    pcm16_back = ulaw_to_pcm16(ulaw)
    # Transcoded back to 16-bit linear PCM should be 320 bytes
    assert len(pcm16_back) == 320


def test_silence_chunks_do_not_trigger_premature_turn():
    """Verify that pure silence chunks accumulate without triggering AI turn or response spam."""
    stream_sid = "exo_silence_test_stream"
    call_sid = "exo_silence_call_001"

    with client.websocket_connect("/exotel/media") as ws:
        # 1. Connected handshake
        ws.send_text(json.dumps({"event": "connected"}))

        # 2. Start event
        ws.send_text(json.dumps({
            "event": "start",
            "stream_sid": stream_sid,
            "start": {
                "call_sid": call_sid,
                "stream_sid": stream_sid,
                "from": "+919876543210"
            }
        }))

        # 3. Send 10 chunks of pure silence (each 20ms = 320 bytes of 0s)
        silence_chunk = base64.b64encode(b"\x00\x00" * 160).decode("ascii")
        for _ in range(10):
            ws.send_text(json.dumps({
                "event": "media",
                "stream_sid": stream_sid,
                "media": {"payload": silence_chunk}
            }))

        # 4. Stop event without any speech
        ws.send_text(json.dumps({
            "event": "stop",
            "stream_sid": stream_sid
        }))

        # No speech occurred, so no outbound media frames should have been generated
        # Connection should close cleanly
        time.sleep(0.1)


def test_exotel_media_websocket_bidirectional_flow():
    """Verify full AgentStream protocol over WS /exotel/media with turn detection:
    - connected
    - start (keyed as EXO-{call_sid})
    - speech audio chunks (accumulated in audio buffer)
    - silence audio chunks (trigger turn detection when speech finishes)
    - ONE outbound media response frame (PCM16 8kHz Base64)
    - dtmf
    - mark
    - clear
    - stop
    """
    stream_sid = "exo_test_stream_999"
    call_sid = "exo_call_sid_12345"
    caller_num = "+919876543210"

    with client.websocket_connect("/exotel/media") as ws:
        # 1. Connected handshake
        ws.send_text(json.dumps({"event": "connected"}))

        # 2. Start event
        ws.send_text(json.dumps({
            "event": "start",
            "stream_sid": stream_sid,
            "start": {
                "call_sid": call_sid,
                "stream_sid": stream_sid,
                "from": caller_num
            }
        }))

        # 3. Send speech chunks: 12 chunks * 20ms = 240ms of active speech (> MIN_SPEECH_DURATION_MS 200ms)
        # Amplitude 2500 has RMS 2500, well above SILENCE_ENERGY_THRESHOLD 400
        speech_pcm16 = struct.pack("<h", 2500) * 160
        speech_b64 = base64.b64encode(speech_pcm16).decode("ascii")
        for _ in range(12):
            ws.send_text(json.dumps({
                "event": "media",
                "stream_sid": stream_sid,
                "media": {"payload": speech_b64}
            }))

        # 4. Send silence chunks: 36 chunks * 20ms = 720ms of silence (> SILENCE_DURATION_MS 700ms)
        silence_pcm16 = b"\x00\x00" * 160
        silence_b64 = base64.b64encode(silence_pcm16).decode("ascii")
        for _ in range(36):
            ws.send_text(json.dumps({
                "event": "media",
                "stream_sid": stream_sid,
                "media": {"payload": silence_b64}
            }))

        # 5. Receive exactly ONE outbound media response frame generated by turn completion
        response_raw = ws.receive_text()
        response_msg = json.loads(response_raw)

        assert response_msg.get("event") == "media"
        assert response_msg.get("stream_sid") == stream_sid
        assert "media" in response_msg
        payload = response_msg["media"].get("payload")
        assert payload is not None

        # Verify payload is valid Base64 PCM16 bytes
        decoded_outbound = base64.b64decode(payload)
        assert len(decoded_outbound) > 0
        assert len(decoded_outbound) % 2 == 0

        # 6. DTMF digit event
        ws.send_text(json.dumps({
            "event": "dtmf",
            "stream_sid": stream_sid,
            "dtmf": {"digit": "5"}
        }))

        # 7. Mark event
        ws.send_text(json.dumps({
            "event": "mark",
            "stream_sid": stream_sid,
            "mark": {"name": "audio_chunk_1"}
        }))

        # 8. Clear event
        ws.send_text(json.dumps({
            "event": "clear",
            "stream_sid": stream_sid
        }))

        # 9. Stop event
        ws.send_text(json.dumps({
            "event": "stop",
            "stream_sid": stream_sid
        }))
        time.sleep(0.1)


@pytest.mark.asyncio
async def test_exotel_session_database_persistence():
    """Verify that Exotel call session was persisted in the database with EXO- prefix."""
    call_sid = "exo_call_sid_12345"
    expected_session_id = f"EXO-{call_sid}"

    sessions = await get_call_sessions(limit=20)
    matching = [s for s in sessions if s["id"] == expected_session_id]
    assert len(matching) == 1
    session = matching[0]
    assert session["id"] == expected_session_id
    assert session["source"] == "exotel"
    assert session["caller_name"] == "+919876543210"
    assert session["status"] == "completed"


def test_protected_routes_unaffected():
    """Verify that existing routes remain fully intact and functional."""
    # Health check
    health_resp = client.get("/health")
    assert health_resp.status_code == 200

    # Vobiz answer webhook
    vobiz_resp = client.post("/vobiz/answer", data={"From": "+1234567890", "CallUUID": "vobiz_test"})
    assert vobiz_resp.status_code == 200
    assert "<Stream" in vobiz_resp.text

    # Calls history API
    history_resp = client.get("/api/calls/history")
    assert history_resp.status_code == 200
    calls_list = history_resp.json()
    assert any(c["id"] == "EXO-exo_call_sid_12345" for c in calls_list)
