"""Tests for Twilio voice webhooks and TwiML generation."""

from fastapi.testclient import TestClient
from twilio.request_validator import RequestValidator
from app.config import settings
from app.main import create_app
from app.models.events import EventType


def test_voice_incoming_twiml_generation():
    """Test /voice/incoming returns valid TwiML with Stream and session parameter."""
    app = create_app()
    client = TestClient(app)

    form_payload = {
        "CallSid": "CA1234567890abcdef",
        "From": "+15550001111",
        "To": "+15550002222",
    }
    response = client.post("/voice/incoming", data=form_payload)
    assert response.status_code == 200
    assert response.headers["content-type"].startswith("application/xml")

    content = response.text
    assert "<Response>" in content
    assert "<Connect>" in content
    assert "<Stream" in content
    assert 'name="session_id"' in content

    # Verify session registered in orchestrator
    orchestrator = app.state.orchestrator
    assert len(orchestrator._sessions) > 0
    created_session = list(orchestrator._sessions.values())[0]
    assert created_session.call_sid == "CA1234567890abcdef"


def test_voice_incoming_signature_validation():
    """Test signature validation using Twilio RequestValidator."""
    app = create_app()
    test_auth_token = "test_auth_token_secret_12345"
    app.state.twilio_service.auth_token = test_auth_token

    client = TestClient(app)
    url = "http://testserver/voice/incoming"
    form_payload = {
        "CallSid": "CA_SECURE_CALL",
        "From": "+19991112222",
        "To": "+19993334444",
    }

    # 1. Invalid signature should return 403
    bad_res = client.post(
        "/voice/incoming",
        data=form_payload,
        headers={"X-Twilio-Signature": "invalid_signature_string"},
    )
    assert bad_res.status_code == 403

    # 2. Valid signature generated by Twilio SDK RequestValidator should succeed (200)
    validator = RequestValidator(test_auth_token)
    valid_signature = validator.compute_signature(url, form_payload)

    good_res = client.post(
        "/voice/incoming",
        data=form_payload,
        headers={"X-Twilio-Signature": valid_signature},
    )
    assert good_res.status_code == 200
    assert "<Response>" in good_res.text


def test_voice_status_callback():
    """Test /voice/status callback completes active session."""
    app = create_app()
    client = TestClient(app)

    # 1. Create incoming call
    res_incoming = client.post(
        "/voice/incoming",
        data={"CallSid": "CA999888777", "From": "+111", "To": "+222"},
    )
    assert res_incoming.status_code == 200

    orchestrator = app.state.orchestrator
    sessions = list(orchestrator._sessions.values())
    assert len(sessions) > 0
    session_id = sessions[0].session_id

    # 2. Post completed status
    res_status = client.post(
        "/voice/status",
        data={"CallSid": "CA999888777", "CallStatus": "completed", "session_id": session_id},
    )
    assert res_status.status_code == 200
    assert res_status.json()["status"] == "received"


