"""Automated test suite for Exotel AgentStream voice bot WebSocket integration in RESCURO.

Tests:
1. Audio format transcoding (PCM16 8kHz <-> G.711 u-law).
2. Silence detection: pure silence chunks do NOT trigger premature turns or response loops.
3. Turn detection: speech chunks followed by silence trigger exactly ONE response turn.
4. Telephony events: connected, start, dtmf, mark, clear, stop.
5. Database session persistence (EXO- prefix).
6. Non-regression of existing routes.
"""

import json
import base64
import struct
import time
import pytest
from fastapi.testclient import TestClient
from app.main import app
from app.services.tts_service import pcm16_to_ulaw, ulaw_to_pcm16
from app.database import get_call_sessions

client = TestClient(app)


def test_exotel_pcm16_ulaw_transcoding_helpers():
    """Verify pcm16_to_ulaw and ulaw_to_pcm16 roundtrip and byte sizing."""
    # 160 samples of 16-bit PCM = 320 bytes
    pcm16_sample = b"\x00\x00" * 160
    assert len(pcm16_sample) == 320

    ulaw = pcm16_to_ulaw(pcm16_sample)
    # 8-bit u-law should be exactly 160 bytes
    assert len(ulaw) == 160

    pcm16_back = ulaw_to_pcm16(ulaw)
    # Transcoded back to 16-bit linear PCM should be 320 bytes
    assert len(pcm16_back) == 320


def test_silence_chunks_do_not_trigger_premature_turn():
    """Verify that pure silence chunks accumulate without triggering AI turn or response spam."""
    stream_sid = "exo_silence_test_stream"
    call_sid = "exo_silence_call_001"

    with client.websocket_connect("/exotel/media") as ws:
        # 1. Connected handshake
        ws.send_text(json.dumps({"event": "connected"}))

        # 2. Start event
        ws.send_text(json.dumps({
            "event": "start",
            "stream_sid": stream_sid,
            "start": {
                "call_sid": call_sid,
                "stream_sid": stream_sid,
                "from": "+919876543210"
            }
        }))

        # 3. Send 10 chunks of pure silence (each 20ms = 320 bytes of 0s)
        silence_chunk = base64.b64encode(b"\x00\x00" * 160).decode("ascii")
        for _ in range(10):
            ws.send_text(json.dumps({
                "event": "media",
                "stream_sid": stream_sid,
                "media": {"payload": silence_chunk}
            }))

        # 4. Stop event without any speech
        ws.send_text(json.dumps({
            "event": "stop",
            "stream_sid": stream_sid
        }))

        # No speech occurred, so no outbound media frames should have been generated
        # Connection should close cleanly
        time.sleep(0.1)


def test_exotel_media_websocket_bidirectional_flow():
    """Verify full AgentStream protocol over WS /exotel/media with turn detection:
    - connected
    - start (keyed as EXO-{call_sid})
    - speech audio chunks (accumulated in audio buffer)
    - silence audio chunks (trigger turn detection when speech finishes)
    - ONE outbound media response frame (PCM16 8kHz Base64)
    - dtmf
    - mark
    - clear
    - stop
    """
    stream_sid = "exo_test_stream_999"
    call_sid = "exo_call_sid_12345"
    caller_num = "+919876543210"

    with client.websocket_connect("/exotel/media") as ws:
        # 1. Connected handshake
        ws.send_text(json.dumps({"event": "connected"}))

        # 2. Start event
        ws.send_text(json.dumps({
            "event": "start",
            "stream_sid": stream_sid,
            "start": {
                "call_sid": call_sid,
                "stream_sid": stream_sid,
                "from": caller_num
            }
        }))

        # 3. Send speech chunks: 12 chunks * 20ms = 240ms of active speech (> MIN_SPEECH_DURATION_MS 200ms)
        # Amplitude 2500 has RMS 2500, well above SILENCE_ENERGY_THRESHOLD 400
        speech_pcm16 = struct.pack("<h", 2500) * 160
        speech_b64 = base64.b64encode(speech_pcm16).decode("ascii")
        for _ in range(12):
            ws.send_text(json.dumps({
                "event": "media",
                "stream_sid": stream_sid,
                "media": {"payload": speech_b64}
            }))

        # 4. Send silence chunks: 36 chunks * 20ms = 720ms of silence (> SILENCE_DURATION_MS 700ms)
        silence_pcm16 = b"\x00\x00" * 160
        silence_b64 = base64.b64encode(silence_pcm16).decode("ascii")
        for _ in range(36):
            ws.send_text(json.dumps({
                "event": "media",
                "stream_sid": stream_sid,
                "media": {"payload": silence_b64}
            }))

        # 5. Receive exactly ONE outbound media response frame generated by turn completion
        response_raw = ws.receive_text()
        response_msg = json.loads(response_raw)

        assert response_msg.get("event") == "media"
        assert response_msg.get("stream_sid") == stream_sid
        assert "media" in response_msg
        payload = response_msg["media"].get("payload")
        assert payload is not None

        # Verify payload is valid Base64 PCM16 bytes
        decoded_outbound = base64.b64decode(payload)
        assert len(decoded_outbound) > 0
        assert len(decoded_outbound) % 2 == 0

        # 6. DTMF digit event
        ws.send_text(json.dumps({
            "event": "dtmf",
            "stream_sid": stream_sid,
            "dtmf": {"digit": "5"}
        }))

        # 7. Mark event
        ws.send_text(json.dumps({
            "event": "mark",
            "stream_sid": stream_sid,
            "mark": {"name": "audio_chunk_1"}
        }))

        # 8. Clear event
        ws.send_text(json.dumps({
            "event": "clear",
            "stream_sid": stream_sid
        }))

        # 9. Stop event
        ws.send_text(json.dumps({
            "event": "stop",
            "stream_sid": stream_sid
        }))
        time.sleep(0.1)


@pytest.mark.asyncio
async def test_exotel_session_database_persistence():
    """Verify that Exotel call session was persisted in the database with EXO- prefix."""
    call_sid = "exo_call_sid_12345"
    expected_session_id = f"EXO-{call_sid}"

    sessions = await get_call_sessions(limit=20)
    matching = [s for s in sessions if s["id"] == expected_session_id]
    assert len(matching) == 1
    session = matching[0]
    assert session["id"] == expected_session_id
    assert session["source"] == "exotel"
    assert session["caller_name"] == "+919876543210"
    assert session["status"] == "completed"


def test_protected_routes_unaffected():
    """Verify that existing routes remain fully intact and functional."""
    # Health check
    health_resp = client.get("/health")
    assert health_resp.status_code == 200

    # Vobiz answer webhook
    vobiz_resp = client.post("/vobiz/answer", data={"From": "+1234567890", "CallUUID": "vobiz_test"})
    assert vobiz_resp.status_code == 200
    assert "<Stream" in vobiz_resp.text

    # Calls history API
    history_resp = client.get("/api/calls/history")
    assert history_resp.status_code == 200
    calls_list = history_resp.json()
    assert any(c["id"] == "EXO-exo_call_sid_12345" for c in calls_list)


from unittest.mock import patch, AsyncMock
from app.services import pipeline


def test_pipeline_turn_stt_succeeds():
    """TEST 1: STT succeeds -> actual transcript is passed to orchestrator."""
    stream_sid = "exo_stream_t1"
    call_sid = "exo_call_t1"
    actual_speech = "There has been a car accident."

    with patch("app.services.pipeline.transcribe_audio", new=AsyncMock(return_value=actual_speech)) as mock_stt:
        with client.websocket_connect("/exotel/media") as ws:
            ws.send_text(json.dumps({"event": "connected"}))
            ws.send_text(json.dumps({
                "event": "start",
                "stream_sid": stream_sid,
                "start": {"call_sid": call_sid, "stream_sid": stream_sid, "from": "+919999999991"}
            }))

            # Send speech (240ms) + silence (720ms)
            speech_b64 = base64.b64encode(struct.pack("<h", 2500) * 160).decode("ascii")
            for _ in range(12):
                ws.send_text(json.dumps({"event": "media", "stream_sid": stream_sid, "media": {"payload": speech_b64}}))
            silence_b64 = base64.b64encode(b"\x00\x00" * 160).decode("ascii")
            for _ in range(36):
                ws.send_text(json.dumps({"event": "media", "stream_sid": stream_sid, "media": {"payload": silence_b64}}))

            # Receive outbound media and mark
            resp_media = json.loads(ws.receive_text())
            assert resp_media.get("event") == "media"
            resp_mark = json.loads(ws.receive_text())
            assert resp_mark.get("event") == "mark"

            # Verify mock_stt was called and actual transcript processed
            assert mock_stt.called
            ws.send_text(json.dumps({"event": "stop", "stream_sid": stream_sid}))


def test_pipeline_turn_stt_fails_no_fake_transcript():
    """TEST 2: STT fails -> NO fake transcript is generated; safe clarification prompt sent."""
    stream_sid = "exo_stream_t2"
    call_sid = "exo_call_t2"

    with patch("app.services.pipeline.transcribe_audio", new=AsyncMock(return_value="")) as mock_stt:
        with patch("app.services.pipeline.run_orchestrator", wraps=pipeline.run_orchestrator) as spy_orch:
            with client.websocket_connect("/exotel/media") as ws:
                ws.send_text(json.dumps({"event": "connected"}))
                ws.send_text(json.dumps({
                    "event": "start",
                    "stream_sid": stream_sid,
                    "start": {"call_sid": call_sid, "stream_sid": stream_sid, "from": "+919999999992"}
                }))

                # Send speech + silence
                speech_b64 = base64.b64encode(struct.pack("<h", 2500) * 160).decode("ascii")
                for _ in range(12):
                    ws.send_text(json.dumps({"event": "media", "stream_sid": stream_sid, "media": {"payload": speech_b64}}))
                silence_b64 = base64.b64encode(b"\x00\x00" * 160).decode("ascii")
                for _ in range(36):
                    ws.send_text(json.dumps({"event": "media", "stream_sid": stream_sid, "media": {"payload": silence_b64}}))

                # Receive outbound media and mark (the safe clarification prompt)
                resp_media = json.loads(ws.receive_text())
                assert resp_media.get("event") == "media"
                resp_mark = json.loads(ws.receive_text())
                assert resp_mark.get("event") == "mark"

                # Orchestrator was NOT called with fake emergency text!
                for call in spy_orch.call_args_list:
                    assert call.kwargs.get("transcript") != "Emergency, I need assistance immediately."
                    if call.args:
                        assert call.args[0] != "Emergency, I need assistance immediately."

                ws.send_text(json.dumps({"event": "stop", "stream_sid": stream_sid}))


def test_caller_multiple_turns_continuity():
    """TEST 3: Multiple turns: Turn 1 (accident) -> Turn 2 (Rajiv Chowk location).
    Expected: two separate transcripts, two orchestrator executions, location preserved in session context."""
    stream_sid = "exo_stream_t3"
    call_sid = "exo_call_t3"

    turn_transcripts = ["There has been a car accident.", "My location is Rajiv Chowk."]
    stt_index = 0

    async def mock_transcribe(*args, **kwargs):
        nonlocal stt_index
        if stt_index < len(turn_transcripts):
            val = turn_transcripts[stt_index]
            stt_index += 1
            return val
        return ""

    with patch("app.services.pipeline.transcribe_audio", side_effect=mock_transcribe):
        with client.websocket_connect("/exotel/media") as ws:
            ws.send_text(json.dumps({"event": "connected"}))
            ws.send_text(json.dumps({
                "event": "start",
                "stream_sid": stream_sid,
                "start": {"call_sid": call_sid, "stream_sid": stream_sid, "from": "+919999999993"}
            }))

            speech_b64 = base64.b64encode(struct.pack("<h", 2500) * 160).decode("ascii")
            silence_b64 = base64.b64encode(b"\x00\x00" * 160).decode("ascii")

            # TURN 1: "There has been a car accident."
            for _ in range(12):
                ws.send_text(json.dumps({"event": "media", "stream_sid": stream_sid, "media": {"payload": speech_b64}}))
            for _ in range(36):
                ws.send_text(json.dumps({"event": "media", "stream_sid": stream_sid, "media": {"payload": silence_b64}}))

            t1_media = json.loads(ws.receive_text())
            assert t1_media["event"] == "media"
            t1_mark = json.loads(ws.receive_text())
            assert t1_mark["event"] == "mark"
            mark1_name = t1_mark["mark"]["name"]

            # Echo mark acknowledgment from Exotel to finish Turn 1 playback
            ws.send_text(json.dumps({"event": "mark", "stream_sid": stream_sid, "mark": {"name": mark1_name}}))

            # TURN 2: "My location is Rajiv Chowk."
            for _ in range(12):
                ws.send_text(json.dumps({"event": "media", "stream_sid": stream_sid, "media": {"payload": speech_b64}}))
            for _ in range(36):
                ws.send_text(json.dumps({"event": "media", "stream_sid": stream_sid, "media": {"payload": silence_b64}}))

            t2_media = json.loads(ws.receive_text())
            assert t2_media["event"] == "media"
            t2_mark = json.loads(ws.receive_text())
            assert t2_mark["event"] == "mark"
            mark2_name = t2_mark["mark"]["name"]

            assert mark1_name != mark2_name
            assert stt_index == 2

            ws.send_text(json.dumps({"event": "stop", "stream_sid": stream_sid}))


def test_caller_says_hello_does_not_repeat_emergency_response():
    """TEST 4: Caller says 'Hello' after emergency response.
    Expected: processed as a new turn; previous emergency response is NOT repeated."""
    stream_sid = "exo_stream_t4"
    call_sid = "exo_call_t4"

    turn_transcripts = ["There has been a car accident.", "Hello"]
    stt_index = 0

    async def mock_transcribe(*args, **kwargs):
        nonlocal stt_index
        if stt_index < len(turn_transcripts):
            val = turn_transcripts[stt_index]
            stt_index += 1
            return val
        return ""

    with patch("app.services.pipeline.transcribe_audio", side_effect=mock_transcribe):
        with client.websocket_connect("/exotel/media") as ws:
            ws.send_text(json.dumps({"event": "connected"}))
            ws.send_text(json.dumps({
                "event": "start",
                "stream_sid": stream_sid,
                "start": {"call_sid": call_sid, "stream_sid": stream_sid, "from": "+919999999994"}
            }))

            speech_b64 = base64.b64encode(struct.pack("<h", 2500) * 160).decode("ascii")
            silence_b64 = base64.b64encode(b"\x00\x00" * 160).decode("ascii")

            # Turn 1: Emergency accident report
            for _ in range(12):
                ws.send_text(json.dumps({"event": "media", "stream_sid": stream_sid, "media": {"payload": speech_b64}}))
            for _ in range(36):
                ws.send_text(json.dumps({"event": "media", "stream_sid": stream_sid, "media": {"payload": silence_b64}}))

            t1_media = json.loads(ws.receive_text())
            t1_mark = json.loads(ws.receive_text())
            ws.send_text(json.dumps({"event": "mark", "stream_sid": stream_sid, "mark": {"name": t1_mark["mark"]["name"]}}))

            # Turn 2: Caller says "Hello"
            for _ in range(12):
                ws.send_text(json.dumps({"event": "media", "stream_sid": stream_sid, "media": {"payload": speech_b64}}))
            for _ in range(36):
                ws.send_text(json.dumps({"event": "media", "stream_sid": stream_sid, "media": {"payload": silence_b64}}))

            t2_media = json.loads(ws.receive_text())
            t2_mark = json.loads(ws.receive_text())

            assert stt_index == 2
            ws.send_text(json.dumps({"event": "stop", "stream_sid": stream_sid}))


def test_outgoing_tts_audio_cannot_trigger_duplicate_turn():
    """TEST 5: Outgoing TTS audio cannot trigger a duplicate turn (Echo suppression).
    Inbound audio sent during assistant playback is suppressed and does NOT trigger an extra turn."""
    stream_sid = "exo_stream_t5"
    call_sid = "exo_call_t5"

    stt_calls = 0

    async def mock_transcribe(*args, **kwargs):
        nonlocal stt_calls
        stt_calls += 1
        return "Help, emergency here."

    with patch("app.services.pipeline.transcribe_audio", side_effect=mock_transcribe):
        with client.websocket_connect("/exotel/media") as ws:
            ws.send_text(json.dumps({"event": "connected"}))
            ws.send_text(json.dumps({
                "event": "start",
                "stream_sid": stream_sid,
                "start": {"call_sid": call_sid, "stream_sid": stream_sid, "from": "+919999999995"}
            }))

            speech_b64 = base64.b64encode(struct.pack("<h", 2500) * 160).decode("ascii")
            silence_b64 = base64.b64encode(b"\x00\x00" * 160).decode("ascii")

            # Turn 1: genuine caller speech
            for _ in range(12):
                ws.send_text(json.dumps({"event": "media", "stream_sid": stream_sid, "media": {"payload": speech_b64}}))
            for _ in range(36):
                ws.send_text(json.dumps({"event": "media", "stream_sid": stream_sid, "media": {"payload": silence_b64}}))

            t1_media = json.loads(ws.receive_text())
            t1_mark = json.loads(ws.receive_text())
            mark_name = t1_mark["mark"]["name"]
            assert stt_calls == 1

            # Simulate telephone bridge echo while assistant is speaking (no mark returned yet)
            echo_b64 = base64.b64encode(struct.pack("<h", 2800) * 160).decode("ascii")
            for _ in range(15):
                ws.send_text(json.dumps({"event": "media", "stream_sid": stream_sid, "media": {"payload": echo_b64}}))
            for _ in range(40):
                ws.send_text(json.dumps({"event": "media", "stream_sid": stream_sid, "media": {"payload": silence_b64}}))

            # Verify no extra turn was executed due to echo
            assert stt_calls == 1

            # Now mark is returned from Exotel acknowledging playback completion
            ws.send_text(json.dumps({"event": "mark", "stream_sid": stream_sid, "mark": {"name": mark_name}}))

            # Next genuine caller speech turn
            for _ in range(12):
                ws.send_text(json.dumps({"event": "media", "stream_sid": stream_sid, "media": {"payload": speech_b64}}))
            for _ in range(36):
                ws.send_text(json.dumps({"event": "media", "stream_sid": stream_sid, "media": {"payload": silence_b64}}))

            t2_media = json.loads(ws.receive_text())
            t2_mark = json.loads(ws.receive_text())
            assert stt_calls == 2

            ws.send_text(json.dumps({"event": "stop", "stream_sid": stream_sid}))


def test_caller_emergency_supervisor_escalation():
    """TEST 6: Caller says 'Emergency. I want to talk to supervisor.' -> routes to supervisor and responds."""
    stream_sid = "exo_stream_t6"
    call_sid = "exo_call_t6"
    supervisor_speech = "Emergency. I want to talk to supervisor."

    with patch("app.services.pipeline.transcribe_audio", new=AsyncMock(return_value=supervisor_speech)):
        with client.websocket_connect("/exotel/media") as ws:
            ws.send_text(json.dumps({"event": "connected"}))
            ws.send_text(json.dumps({
                "event": "start",
                "stream_sid": stream_sid,
                "start": {"call_sid": call_sid, "stream_sid": stream_sid, "from": "+919999999996"}
            }))

            speech_b64 = base64.b64encode(struct.pack("<h", 2500) * 160).decode("ascii")
            for _ in range(12):
                ws.send_text(json.dumps({"event": "media", "stream_sid": stream_sid, "media": {"payload": speech_b64}}))
            silence_b64 = base64.b64encode(b"\x00\x00" * 160).decode("ascii")
            for _ in range(36):
                ws.send_text(json.dumps({"event": "media", "stream_sid": stream_sid, "media": {"payload": silence_b64}}))

            resp_media = json.loads(ws.receive_text())
            assert resp_media.get("event") == "media"
            resp_mark = json.loads(ws.receive_text())
            assert resp_mark.get("event") == "mark"

            ws.send_text(json.dumps({"event": "stop", "stream_sid": stream_sid}))
